// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// euclideanDistance
double euclideanDistance(const arma::vec& x, const arma::vec& y);
RcppExport SEXP _sclValid_euclideanDistance(SEXP xSEXP, SEXP ySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type x(xSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type y(ySEXP);
    rcpp_result_gen = Rcpp::wrap(euclideanDistance(x, y));
    return rcpp_result_gen;
END_RCPP
}
// rowMeansC
Rcpp::NumericVector rowMeansC(Rcpp::NumericMatrix mat);
RcppExport SEXP _sclValid_rowMeansC(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericMatrix >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(rowMeansC(mat));
    return rcpp_result_gen;
END_RCPP
}
// list_nn
List list_nn(const arma::mat& mat, int k);
RcppExport SEXP _sclValid_list_nn(SEXP matSEXP, SEXP kSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    Rcpp::traits::input_parameter< int >::type k(kSEXP);
    rcpp_result_gen = Rcpp::wrap(list_nn(mat, k));
    return rcpp_result_gen;
END_RCPP
}
// dist_mat
arma::mat dist_mat(const arma::mat& mat);
RcppExport SEXP _sclValid_dist_mat(SEXP matSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::mat& >::type mat(matSEXP);
    rcpp_result_gen = Rcpp::wrap(dist_mat(mat));
    return rcpp_result_gen;
END_RCPP
}
// SilhouetteDistancecpp
double SilhouetteDistancecpp(const Rcpp::NumericVector& ocp, const Rcpp::NumericMatrix& distmat);
RcppExport SEXP _sclValid_SilhouetteDistancecpp(SEXP ocpSEXP, SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const Rcpp::NumericVector& >::type ocp(ocpSEXP);
    Rcpp::traits::input_parameter< const Rcpp::NumericMatrix& >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(SilhouetteDistancecpp(ocp, distmat));
    return rcpp_result_gen;
END_RCPP
}
// create_contingency_table
arma::mat create_contingency_table(Rcpp::NumericVector rcjk, Rcpp::NumericVector ocjk);
RcppExport SEXP _sclValid_create_contingency_table(SEXP rcjkSEXP, SEXP ocjkSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type rcjk(rcjkSEXP);
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ocjk(ocjkSEXP);
    rcpp_result_gen = Rcpp::wrap(create_contingency_table(rcjk, ocjk));
    return rcpp_result_gen;
END_RCPP
}
// DunnIndexCpp
double DunnIndexCpp(Rcpp::NumericVector ocp, arma::mat distmat);
RcppExport SEXP _sclValid_DunnIndexCpp(SEXP ocpSEXP, SEXP distmatSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::NumericVector >::type ocp(ocpSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type distmat(distmatSEXP);
    rcpp_result_gen = Rcpp::wrap(DunnIndexCpp(ocp, distmat));
    return rcpp_result_gen;
END_RCPP
}
// BioSIndexCpp
double BioSIndexCpp(const arma::vec& oc, const arma::vec& bd, const Rcpp::List& rc);
RcppExport SEXP _sclValid_BioSIndexCpp(SEXP ocSEXP, SEXP bdSEXP, SEXP rcSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const arma::vec& >::type oc(ocSEXP);
    Rcpp::traits::input_parameter< const arma::vec& >::type bd(bdSEXP);
    Rcpp::traits::input_parameter< const Rcpp::List& >::type rc(rcSEXP);
    rcpp_result_gen = Rcpp::wrap(BioSIndexCpp(oc, bd, rc));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_sclValid_euclideanDistance", (DL_FUNC) &_sclValid_euclideanDistance, 2},
    {"_sclValid_rowMeansC", (DL_FUNC) &_sclValid_rowMeansC, 1},
    {"_sclValid_list_nn", (DL_FUNC) &_sclValid_list_nn, 2},
    {"_sclValid_dist_mat", (DL_FUNC) &_sclValid_dist_mat, 1},
    {"_sclValid_SilhouetteDistancecpp", (DL_FUNC) &_sclValid_SilhouetteDistancecpp, 2},
    {"_sclValid_create_contingency_table", (DL_FUNC) &_sclValid_create_contingency_table, 2},
    {"_sclValid_DunnIndexCpp", (DL_FUNC) &_sclValid_DunnIndexCpp, 2},
    {"_sclValid_BioSIndexCpp", (DL_FUNC) &_sclValid_BioSIndexCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_sclValid(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
