# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

euclideanDistance <- function(x, y) {
    .Call(`_sclValid_euclideanDistance`, x, y)
}

rowMeansC <- function(mat) {
    .Call(`_sclValid_rowMeansC`, mat)
}

list_nn <- function(mat, k = 10L) {
    .Call(`_sclValid_list_nn`, mat, k)
}

dist_mat <- function(mat) {
    .Call(`_sclValid_dist_mat`, mat)
}

SilhouetteDistancecpp <- function(ocp, distmat) {
    .Call(`_sclValid_SilhouetteDistancecpp`, ocp, distmat)
}

create_contingency_table <- function(rcjk, ocjk) {
    .Call(`_sclValid_create_contingency_table`, rcjk, ocjk)
}

DunnIndexCpp <- function(ocp, distmat) {
    .Call(`_sclValid_DunnIndexCpp`, ocp, distmat)
}

BioSIndexCpp <- function(oc, bd, rc) {
    .Call(`_sclValid_BioSIndexCpp`, oc, bd, rc)
}

